import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/apiAuth";
import {
  generateTitle,
  generateSKU,
  generateSEOTitle,
  generateSEODescription,
  generatePageUrl,
  generateTags,
  generateHTMLDescription,
  calculateDiscountedPrice,
} from "@/lib/autoGenerate";
import { deleteProduct } from "@/lib/shopify";
import {
  fetchProductsForPush,
  pushProductsToShopify,
} from "@/lib/shopifyPush";
import { logActivity } from "@/lib/activityLog";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await requireAuth();
    if (!auth.authorized) return auth.response!;
    const { id } = await params;
    const product = await prisma.product.findUnique({
      where: { id },
      include: {
        images: true,
        locations: true,
        syncLogs: true,
        variants: {
          include: {
            images: true,
            locations: { include: { location: true } },
          },
        },
      },
    });

    if (!product) {
      return NextResponse.json(
        { success: false, error: "Product not found" },
        { status: 404 }
      );
    }

    return NextResponse.json({ success: true, data: product }, { status: 200 });
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}

// Use flexible typing for update requests
type UpdateProductRequest = Record<string, any>;

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await requireAuth(["ADMIN", "CATALOG_MANAGER"]);
    if (!auth.authorized) return auth.response!;
    const { id } = await params;

    const body: UpdateProductRequest = await request.json();

    const product = await prisma.product.findUnique({
      where: { id },
      include: { variants: true },
    });

    if (!product) {
      return NextResponse.json(
        { success: false, error: "Product not found" },
        { status: 404 }
      );
    }

    const mergedProduct = { ...product, ...body };
    const discountRules = await prisma.discountRule.findMany();

    const autoGeneratedData = {
      title: body.title || generateTitle(mergedProduct),
      sku: generateSKU(mergedProduct),
      seoTitle: generateSEOTitle(mergedProduct),
      seoDescription: generateSEODescription(mergedProduct),
      pageUrl: generatePageUrl(mergedProduct),
      tags: generateTags(mergedProduct),
      htmlDescription: generateHTMLDescription(mergedProduct),
      discountedPrice: calculateDiscountedPrice(
        body.mrp || product.mrp,
        body.category || product.category,
        discountRules,
        body.brand || product.brand,
        body.subBrand || product.subBrand
      ),
    };

    // Build update data via an EXPLICIT allowlist of Product model
    // columns. The edit form (and historic /api/products payloads) sends
    // a much wider set of fields — variant-level columns, dynamic
    // category attrs, typo'd keys like `bridgeWidth` — and a permissive
    // `...spread` would hand all of those to prisma.product.update,
    // which fails with "Unknown argument" for anything not on the model.
    // The allowlist keeps the handler tolerant: unknown keys are
    // silently dropped instead of breaking the whole save.
    const PRODUCT_FIELDS = [
      "category",
      "status",
      "brand",
      "subBrand",
      "label",
      "productName",
      "modelNo",
      "fullModelNo",
      "shape",
      "frameMaterial",
      "templeMaterial",
      "frameType",
      "gender",
      "countryOfOrigin",
      "warranty",
      "lensMaterial",
      "lensUSP",
      "polarization",
      "uvProtection",
      "productUSP",
      "recommendedFor",
      "instructions",
      "ingredients",
      "benefits",
      "aboutProduct",
      "mrp",
      "compareAtPrice",
      "gtin",
      "upc",
      "imageDesignStatus",
    ] as const;
    const updateData: Record<string, any> = {};
    for (const k of PRODUCT_FIELDS) {
      if (Object.prototype.hasOwnProperty.call(body, k)) {
        updateData[k] = (body as Record<string, unknown>)[k];
      }
    }
    // Auto-generated fields always overwrite — they're derived from the
    // merged product, not user input.
    updateData.title = autoGeneratedData.title;
    updateData.sku = autoGeneratedData.sku;
    updateData.seoTitle = autoGeneratedData.seoTitle;
    updateData.seoDescription = autoGeneratedData.seoDescription;
    updateData.pageUrl = autoGeneratedData.pageUrl;
    updateData.tags = autoGeneratedData.tags;
    updateData.htmlDescription = autoGeneratedData.htmlDescription;
    updateData.discountedPrice = autoGeneratedData.discountedPrice;
    // images and locations come in the body but are handled separately
    // below — pull them out of the variable so the linter doesn't
    // complain about an unused destructure.
    const images = (body as Record<string, unknown>).images;
    const locations = (body as Record<string, unknown>).locations;
    void images;
    void locations;

    const updatedProduct = await prisma.product.update({
      where: { id: id },
      data: updateData,
      include: {
        images: true,
        locations: true,
        syncLogs: true,
      },
    });

    // Push to Shopify whenever the user requested status=PUBLISHED.
    // Two cases:
    //   A. Product was already on Shopify (had shopifyProductId before
    //      this update) → "update" mode pushes title/description/SEO/
    //      tags/vendor/productType/metafields + variant prices via the
    //      shared pushProductsToShopify helper.
    //   B. Product is brand new to Shopify (orphan being published for
    //      the first time) → "skip" mode (default). The helper sees no
    //      shopifyProductId and runs createProduct which mints a fresh
    //      Shopify product, links shopifyProductId + variant IDs, sets
    //      all 16 product metafields and 8 per-variant metafields,
    //      auto-assigns to brand/category collections.
    //
    // Either way the helper writes a SyncLog row, so we don't have to
    // duplicate that here. shopifyPushError is surfaced in the JSON
    // response so the client can show the real reason instead of a
    // generic "Error updating product".
    let shopifyPushError: string | null = null;
    let shopifyPushSuccess = false;
    const shouldPush = body.status === "PUBLISHED";

    if (shouldPush) {
      try {
        const products = await fetchProductsForPush([id]);
        if (products.length === 0) {
          shopifyPushError = "Product not found for Shopify push";
        } else {
          const wasAlreadySynced = !!product.shopifyProductId;
          const { results, summary } = await pushProductsToShopify(products, {
            // For first-time publish use "skip" (the default — only
            // creates new). For products already on Shopify we want
            // "update" so the edit actually re-pushes title/tags/etc.
            syncedMode: wasAlreadySynced ? "update" : "skip",
          });
          // pushProductsToShopify returns one result per product. We
          // pushed exactly 1, so look at results[0].
          const r = results[0];
          if (r && r.status === "SUCCESS") {
            shopifyPushSuccess = true;
          } else {
            shopifyPushError =
              r?.message ||
              summary.abortReason ||
              "Shopify push failed (no detail returned)";
          }
        }
      } catch (e) {
        shopifyPushError =
          e instanceof Error ? e.message : "Shopify push threw an exception";
      }

      // If the local update succeeded but Shopify rejected, leave the
      // local status PUBLISHED — the user explicitly asked for that —
      // but make sure the alert surfaces the failure so they can fix
      // and retry. SyncLog row is already created inside the helper.
    }

    // Log activity
    logActivity({
      userId: (auth.session?.user as any)?.id,
      userName: auth.session?.user?.name,
      userEmail: auth.session?.user?.email,
      action: "UPDATE",
      entity: "PRODUCT",
      entityId: id,
      details: `Updated product: ${updatedProduct.title || updatedProduct.brand}`,
    });

    // If the caller requested PUBLISHED and the Shopify push failed,
    // return success=false with a 200 + a structured payload so the
    // edit page can surface the Shopify error in its alert. Local
    // changes have already been saved either way.
    if (shouldPush && shopifyPushError) {
      return NextResponse.json(
        {
          success: false,
          error: `Saved locally, but Shopify rejected the push: ${shopifyPushError}`,
          shopifyError: shopifyPushError,
          data: updatedProduct,
          autoGenerated: autoGeneratedData,
        },
        { status: 200 }
      );
    }

    return NextResponse.json(
      {
        success: true,
        data: updatedProduct,
        autoGenerated: autoGeneratedData,
        shopifyPushed: shopifyPushSuccess,
      },
      { status: 200 }
    );
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await requireAuth(["ADMIN", "CATALOG_MANAGER"]);
    if (!auth.authorized) return auth.response!;
    const { id } = await params;

    const product = await prisma.product.findUnique({
      where: { id: id },
    });

    if (!product) {
      return NextResponse.json(
        { success: false, error: "Product not found" },
        { status: 404 }
      );
    }

    await prisma.product.update({
      where: { id: id },
      data: { status: "ARCHIVED" },
    });

    if (product.shopifyProductId) {
      const shopifyResult = await deleteProduct(product.shopifyProductId);

      await prisma.syncLog.create({
        data: {
          productId: id,
          action: "DELETE",
          status: shopifyResult.success ? "SUCCESS" : "FAILED",
          message: shopifyResult.message,
        },
      });
    }

    // Log activity
    logActivity({
      userId: (auth.session?.user as any)?.id,
      userName: auth.session?.user?.name,
      userEmail: auth.session?.user?.email,
      action: "DELETE",
      entity: "PRODUCT",
      entityId: id,
      details: `Archived product: ${product.title || product.brand} (${product.sku || 'no-sku'})`,
    });

    return NextResponse.json(
      { success: true, message: "Product archived successfully" },
      { status: 200 }
    );
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}
