import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/apiAuth";
import {
  generateTitle,
  generateSKU,
  generateSEOTitle,
  generateSEODescription,
  generatePageUrl,
  generateTags,
  generateHTMLDescription,
  calculateDiscountedPrice,
} from "@/lib/autoGenerate";
import {
  updateProduct,
  deleteProduct,
  updateVariantPrice,
  setProductMetafields,
} from "@/lib/shopify";
import { categoryLabel } from "@/lib/categories";
import { logActivity } from "@/lib/activityLog";

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const auth = await requireAuth();
    if (!auth.authorized) return auth.response!;
    const product = await prisma.product.findUnique({
      where: { id: params.id },
      include: {
        images: true,
        locations: true,
        syncLogs: true,
        variants: {
          include: {
            images: true,
            locations: { include: { location: true } },
          },
        },
      },
    });

    if (!product) {
      return NextResponse.json(
        { success: false, error: "Product not found" },
        { status: 404 }
      );
    }

    return NextResponse.json({ success: true, data: product }, { status: 200 });
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}

// Use flexible typing for update requests
type UpdateProductRequest = Record<string, any>;

export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const auth = await requireAuth(["ADMIN", "CATALOG_MANAGER"]);
    if (!auth.authorized) return auth.response!;

    const body: UpdateProductRequest = await request.json();

    const product = await prisma.product.findUnique({
      where: { id: params.id },
      include: { variants: true },
    });

    if (!product) {
      return NextResponse.json(
        { success: false, error: "Product not found" },
        { status: 404 }
      );
    }

    const mergedProduct = { ...product, ...body };
    const discountRules = await prisma.discountRule.findMany();

    const autoGeneratedData = {
      title: body.title || generateTitle(mergedProduct),
      sku: generateSKU(mergedProduct),
      seoTitle: generateSEOTitle(mergedProduct),
      seoDescription: generateSEODescription(mergedProduct),
      pageUrl: generatePageUrl(mergedProduct),
      tags: generateTags(mergedProduct),
      htmlDescription: generateHTMLDescription(mergedProduct),
      discountedPrice: calculateDiscountedPrice(
        body.mrp || product.mrp,
        body.category || product.category,
        discountRules,
        body.brand || product.brand,
        body.subBrand || product.subBrand
      ),
    };

    // Build update data via an EXPLICIT allowlist of Product model
    // columns. The edit form (and historic /api/products payloads) sends
    // a much wider set of fields — variant-level columns, dynamic
    // category attrs, typo'd keys like `bridgeWidth` — and a permissive
    // `...spread` would hand all of those to prisma.product.update,
    // which fails with "Unknown argument" for anything not on the model.
    // The allowlist keeps the handler tolerant: unknown keys are
    // silently dropped instead of breaking the whole save.
    const PRODUCT_FIELDS = [
      "category",
      "status",
      "brand",
      "subBrand",
      "label",
      "productName",
      "modelNo",
      "fullModelNo",
      "shape",
      "frameMaterial",
      "templeMaterial",
      "frameType",
      "gender",
      "countryOfOrigin",
      "warranty",
      "lensMaterial",
      "lensUSP",
      "polarization",
      "uvProtection",
      "productUSP",
      "recommendedFor",
      "instructions",
      "ingredients",
      "benefits",
      "aboutProduct",
      "mrp",
      "compareAtPrice",
      "gtin",
      "upc",
      "imageDesignStatus",
    ] as const;
    const updateData: Record<string, any> = {};
    for (const k of PRODUCT_FIELDS) {
      if (Object.prototype.hasOwnProperty.call(body, k)) {
        updateData[k] = (body as Record<string, unknown>)[k];
      }
    }
    // Auto-generated fields always overwrite — they're derived from the
    // merged product, not user input.
    updateData.title = autoGeneratedData.title;
    updateData.sku = autoGeneratedData.sku;
    updateData.seoTitle = autoGeneratedData.seoTitle;
    updateData.seoDescription = autoGeneratedData.seoDescription;
    updateData.pageUrl = autoGeneratedData.pageUrl;
    updateData.tags = autoGeneratedData.tags;
    updateData.htmlDescription = autoGeneratedData.htmlDescription;
    updateData.discountedPrice = autoGeneratedData.discountedPrice;
    // images and locations come in the body but are handled separately
    // below — pull them out of the variable so the linter doesn't
    // complain about an unused destructure.
    const images = (body as Record<string, unknown>).images;
    const locations = (body as Record<string, unknown>).locations;
    void images;
    void locations;

    const updatedProduct = await prisma.product.update({
      where: { id: params.id },
      data: updateData,
      include: {
        images: true,
        locations: true,
        syncLogs: true,
      },
    });

    if (product.shopifyProductId && product.status === "PUBLISHED") {
      // Audit fix: send vendor + human-label productType + filtered tags
      // on every update so subsequent edits don't silently revert to the
      // store's default vendor or stale productType casing.
      const shopifyResult = await updateProduct(product.shopifyProductId, {
        title: autoGeneratedData.title,
        description: autoGeneratedData.htmlDescription,
        seoTitle: autoGeneratedData.seoTitle,
        seoDescription: autoGeneratedData.seoDescription,
        tags: autoGeneratedData.tags
          ?.split(", ")
          .map((t: string) => t.trim())
          .filter(Boolean),
        productType:
          categoryLabel(product.category) || product.category || undefined,
        vendor: updatedProduct.brand || product.brand || undefined,
        status: "ACTIVE",
      } as any);

      // Sync variant prices to Shopify. Bail out after 5 consecutive failures
      // — without this cap, a product with 60+ variants in a throttle storm
      // would churn through every variant × the GraphQL client's internal
      // retries before returning a single error to the user.
      if (shopifyResult.success) {
        const variants = await prisma.productVariant.findMany({
          where: { productId: params.id, shopifyVariantId: { not: null } },
        });
        let consecutiveVariantFailures = 0;
        const MAX_VARIANT_FAILURES = 5;
        for (const v of variants) {
          if (!v.shopifyVariantId) continue;
          const r = await updateVariantPrice(
            v.shopifyVariantId,
            String(v.discountedPrice || v.mrp || 0),
            v.mrp ? String(v.mrp) : undefined
          ).catch(() => ({ success: false } as { success: boolean }));
          if (r && (r as any).success) {
            consecutiveVariantFailures = 0;
          } else {
            consecutiveVariantFailures++;
            if (consecutiveVariantFailures >= MAX_VARIANT_FAILURES) {
              console.warn(
                `[products/${params.id}] Aborting variant price sync after ${consecutiveVariantFailures} consecutive failures.`
              );
              break;
            }
          }
        }

        // Re-push product-level metafields on every update so changes to
        // shape, materials, polarization, etc. flow back to Shopify. Best-
        // effort — failure here doesn't fail the whole product update.
        const productMfs: Array<{
          namespace: string;
          key: string;
          value: string;
          type: string;
        }> = [];
        const pushPMf = (key: string, value: string | null | undefined) => {
          if (value && String(value).trim()) {
            productMfs.push({
              namespace: "custom",
              key,
              value: String(value).trim(),
              type: "single_line_text_field",
            });
          }
        };
        pushPMf("brand", updatedProduct.brand);
        pushPMf("sub_brand", updatedProduct.subBrand);
        pushPMf("model_no", updatedProduct.modelNo);
        pushPMf("label", updatedProduct.label);
        pushPMf("shape", updatedProduct.shape);
        pushPMf("frame_material", updatedProduct.frameMaterial);
        pushPMf("temple_material", updatedProduct.templeMaterial);
        pushPMf("frame_type", updatedProduct.frameType);
        pushPMf("lens_material", updatedProduct.lensMaterial);
        pushPMf("polarization", updatedProduct.polarization);
        pushPMf("uv_protection", updatedProduct.uvProtection);
        pushPMf("gender", updatedProduct.gender);
        pushPMf("country_of_origin", updatedProduct.countryOfOrigin);
        pushPMf("warranty", updatedProduct.warranty);
        pushPMf("product_usp", updatedProduct.productUSP);
        if (productMfs.length > 0) {
          await setProductMetafields(
            product.shopifyProductId,
            productMfs
          ).catch(() => {});
        }
      }

      await prisma.syncLog.create({
        data: {
          productId: params.id,
          action: "UPDATE",
          status: shopifyResult.success ? "SUCCESS" : "FAILED",
          message: shopifyResult.message,
        },
      });
    }

    // Log activity
    logActivity({
      userId: (auth.session?.user as any)?.id,
      userName: auth.session?.user?.name,
      userEmail: auth.session?.user?.email,
      action: "UPDATE",
      entity: "PRODUCT",
      entityId: params.id,
      details: `Updated product: ${updatedProduct.title || updatedProduct.brand}`,
    });

    return NextResponse.json(
      {
        success: true,
        data: updatedProduct,
        autoGenerated: autoGeneratedData,
      },
      { status: 200 }
    );
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const auth = await requireAuth(["ADMIN", "CATALOG_MANAGER"]);
    if (!auth.authorized) return auth.response!;

    const product = await prisma.product.findUnique({
      where: { id: params.id },
    });

    if (!product) {
      return NextResponse.json(
        { success: false, error: "Product not found" },
        { status: 404 }
      );
    }

    await prisma.product.update({
      where: { id: params.id },
      data: { status: "ARCHIVED" },
    });

    if (product.shopifyProductId) {
      const shopifyResult = await deleteProduct(product.shopifyProductId);

      await prisma.syncLog.create({
        data: {
          productId: params.id,
          action: "DELETE",
          status: shopifyResult.success ? "SUCCESS" : "FAILED",
          message: shopifyResult.message,
        },
      });
    }

    // Log activity
    logActivity({
      userId: (auth.session?.user as any)?.id,
      userName: auth.session?.user?.name,
      userEmail: auth.session?.user?.email,
      action: "DELETE",
      entity: "PRODUCT",
      entityId: params.id,
      details: `Archived product: ${product.title || product.brand} (${product.sku || 'no-sku'})`,
    });

    return NextResponse.json(
      { success: true, message: "Product archived successfully" },
      { status: 200 }
    );
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}
