import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/apiAuth";
import {
  generateTitle,
  generateSKU,
  generateSEOTitle,
  generateSEODescription,
  generatePageUrl,
  generateTags,
  generateHTMLDescription,
  calculateDiscountedPrice,
} from "@/lib/autoGenerate";
import { updateProduct, deleteProduct, updateVariantPrice } from "@/lib/shopify";
import { logActivity } from "@/lib/activityLog";

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const auth = await requireAuth();
    if (!auth.authorized) return auth.response!;
    const product = await prisma.product.findUnique({
      where: { id: params.id },
      include: {
        images: true,
        locations: true,
        syncLogs: true,
        variants: {
          include: {
            images: true,
            locations: { include: { location: true } },
          },
        },
      },
    });

    if (!product) {
      return NextResponse.json(
        { success: false, error: "Product not found" },
        { status: 404 }
      );
    }

    return NextResponse.json({ success: true, data: product }, { status: 200 });
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}

// Use flexible typing for update requests
type UpdateProductRequest = Record<string, any>;

export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const auth = await requireAuth(["ADMIN", "CATALOG_MANAGER"]);
    if (!auth.authorized) return auth.response!;

    const body: UpdateProductRequest = await request.json();

    const product = await prisma.product.findUnique({
      where: { id: params.id },
      include: { variants: true },
    });

    if (!product) {
      return NextResponse.json(
        { success: false, error: "Product not found" },
        { status: 404 }
      );
    }

    const mergedProduct = { ...product, ...body };
    const discountRules = await prisma.discountRule.findMany();

    const autoGeneratedData = {
      title: body.title || generateTitle(mergedProduct),
      sku: generateSKU(mergedProduct),
      seoTitle: generateSEOTitle(mergedProduct),
      seoDescription: generateSEODescription(mergedProduct),
      pageUrl: generatePageUrl(mergedProduct),
      tags: generateTags(mergedProduct),
      htmlDescription: generateHTMLDescription(mergedProduct),
      discountedPrice: calculateDiscountedPrice(
        body.mrp || product.mrp,
        body.category || product.category,
        discountRules,
        body.brand || product.brand,
        body.subBrand || product.subBrand
      ),
    };

    // Build update data: spread user fields + auto-generated fields.
    // Strip legacy variant-level columns that were removed from Product
    // (edit form still sends them in FormData, but they now only live on
    // ProductVariant).
    const {
      images,
      locations,
      colorCode: _colorCode,
      frameColor: _frameColor,
      templeColor: _templeColor,
      frameSize: _frameSize,
      bridge: _bridge,
      templeLength: _templeLength,
      weight: _weight,
      lensColour: _lensColour,
      tint: _tint,
      ...productFields
    } = body;
    void _colorCode;
    void _frameColor;
    void _templeColor;
    void _frameSize;
    void _bridge;
    void _templeLength;
    void _weight;
    void _lensColour;
    void _tint;
    const updateData: Record<string, any> = {
      ...productFields,
      title: autoGeneratedData.title,
      sku: autoGeneratedData.sku,
      seoTitle: autoGeneratedData.seoTitle,
      seoDescription: autoGeneratedData.seoDescription,
      pageUrl: autoGeneratedData.pageUrl,
      tags: autoGeneratedData.tags,
      htmlDescription: autoGeneratedData.htmlDescription,
      discountedPrice: autoGeneratedData.discountedPrice,
    };

    const updatedProduct = await prisma.product.update({
      where: { id: params.id },
      data: updateData,
      include: {
        images: true,
        locations: true,
        syncLogs: true,
      },
    });

    if (product.shopifyProductId && product.status === "PUBLISHED") {
      const shopifyResult = await updateProduct(product.shopifyProductId, {
        title: autoGeneratedData.title,
        description: autoGeneratedData.htmlDescription,
        seoTitle: autoGeneratedData.seoTitle,
        seoDescription: autoGeneratedData.seoDescription,
        tags: autoGeneratedData.tags?.split(", "),
        productType: product.category || undefined,
      } as any);

      // Sync variant prices to Shopify
      if (shopifyResult.success) {
        const variants = await prisma.productVariant.findMany({
          where: { productId: params.id, shopifyVariantId: { not: null } },
        });
        for (const v of variants) {
          if (v.shopifyVariantId) {
            await updateVariantPrice(
              v.shopifyVariantId,
              String(v.discountedPrice || v.mrp || 0),
              v.mrp ? String(v.mrp) : undefined
            ).catch(() => {}); // Best-effort variant sync
          }
        }
      }

      await prisma.syncLog.create({
        data: {
          productId: params.id,
          action: "UPDATE",
          status: shopifyResult.success ? "SUCCESS" : "FAILED",
          message: shopifyResult.message,
        },
      });
    }

    // Log activity
    logActivity({
      userId: (auth.session?.user as any)?.id,
      userName: auth.session?.user?.name,
      userEmail: auth.session?.user?.email,
      action: "UPDATE",
      entity: "PRODUCT",
      entityId: params.id,
      details: `Updated product: ${updatedProduct.title || updatedProduct.brand}`,
    });

    return NextResponse.json(
      {
        success: true,
        data: updatedProduct,
        autoGenerated: autoGeneratedData,
      },
      { status: 200 }
    );
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const auth = await requireAuth(["ADMIN", "CATALOG_MANAGER"]);
    if (!auth.authorized) return auth.response!;

    const product = await prisma.product.findUnique({
      where: { id: params.id },
    });

    if (!product) {
      return NextResponse.json(
        { success: false, error: "Product not found" },
        { status: 404 }
      );
    }

    await prisma.product.update({
      where: { id: params.id },
      data: { status: "ARCHIVED" },
    });

    if (product.shopifyProductId) {
      const shopifyResult = await deleteProduct(product.shopifyProductId);

      await prisma.syncLog.create({
        data: {
          productId: params.id,
          action: "DELETE",
          status: shopifyResult.success ? "SUCCESS" : "FAILED",
          message: shopifyResult.message,
        },
      });
    }

    // Log activity
    logActivity({
      userId: (auth.session?.user as any)?.id,
      userName: auth.session?.user?.name,
      userEmail: auth.session?.user?.email,
      action: "DELETE",
      entity: "PRODUCT",
      entityId: params.id,
      details: `Archived product: ${product.title || product.brand} (${product.sku || 'no-sku'})`,
    });

    return NextResponse.json(
      { success: true, message: "Product archived successfully" },
      { status: 200 }
    );
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}
